### ISSUE TITLE
Computer Sciences -> Computer Science (typo)

### ISSUE THREAD

**Issue by eliasgruenewald** [maroulb/SpringerCoronaBooks#2]
https://github.com/maroulb/SpringerCoronaBooks/blob/cbe5a74e7e2456379eae73709c00c1ff6243a562/spricobo.py#L34

This should be `wishlist.append('Computer Science')` in order to work correctly. ;-)

**Comment by maroulb** [comment]
not mission critical (works like expected, because 'Computer Science' is always in 'Computer Sciences'), but solved. thx.
